### ISSUE TITLE
Player Displayer v1.4.5 keeps crashing after finding opponents

### ISSUE THREAD

**Issue by KyoDEG** [ParadiseAigo/Tekken-7-Player-Displayer#44] opened 2023-03-24 23:57 UTC
Basically title. Sometimes it's functional for hours and sometimes it closes every other opponent. Any ideas?

What I've tried: Redownloading, starting as administrator, restart game + program. Still persists. 
It doesn't seem related to a specific country, player or anything like that it can close itself on opponents it didn't have an issue against previously so I'm at a loss honestly. I don't remember this happening before the country display was added.

OS: win 11

**Comment by ParadiseAigo** [comment] 2023-04-25 01:14
Thanks for the feedback.

Yes I can confirm it was crashing a lot about a month ago now when I tested it. The crashes always happened right after being matched with someone. It turns out that these crashes were basically caused by the part of the program that gets the name from the Steam web servers. Steam must have changed something which caused all the crashes.

In any case, it should be fixed now. (see the latest release)

**Closed as completed** 2024-02-22 13:09 UTC
